name: "Setup NodeJS"
description: "Install NodeJS and enable yarn"
runs:
  using: "composite"
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 24.13.1
    - name: Enable yarn
      shell: bash
      run: corepack enable
