[toolchain]
anchor_version = "0.32.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_usd_oracle = "E5HbJS2cXteHwBUdRDWmUkp5Q3oaf3TBZz1rK4jnCzxx"
token_minter = "CfAKuB2StvSWcmirGmQ5RFqib1rcgRTziSXuKQR3ptgE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
exclude = ["programs/tests"]

[scripts]
test = "cargo test"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
