[package]
name = "tests"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-client = "0.32.1"
anchor-spl = { version = "0.32.1", features = ["token", "associated_token"] }
solana-keypair = "2.2.3"
solana-pubkey = "2.3.0"
anyhow = "1"
sol-usd-oracle = { path = "../sol_usd_oracle", version = "0.1.0", features = ["default"] }
token-minter = { path = "../token_minter", version = "0.1.0" }
anchor-lang = "0.32.1"
solana-sdk = "2.3.1"
litesvm = "0.7.1"

[[example]]
name = "init-accounts"
path = "examples/init-accounts.rs"

[[example]]
name = "get-oracle-pda"
path = "examples/get-oracle-pda.rs"